version: 2
jobs:
  unit_tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "jsondsl/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "jsondsl/build.gradle" }}
      - run:
          name: Install Fastlane
          command: bundle check || bundle update && bundle install --path vendor/bundle
      - run:
          name: Code coverage report
          command: bundle exec fastlane android coverage
      - run:
          name: Run Tests
          command: bundle exec fastlane test
      - store_artifacts:
          path: jsondsl/build/reports
          destination: reports
      - store_test_results:
          path: jsondsl/build/test-results

workflows:
  version: 2
  test:
    jobs:
      - unit_tests